# Generated by Django 3.2.6 on 2021-09-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets_ch2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Draft'),
        ),
    ]
