# Generated by Django 3.2.6 on 2021-09-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='created_st',
            new_name='created_at',
        ),
    ]
